<?php
/** 
 * SGU Blocks Class
 * 
 * Handles Gutenberg block registration and rendering for astronomy-related blocks.
 * Provides block editor integration with real-time previews and delegates rendering
 * to existing shortcode infrastructure on the front-end.
 * 
 * @since 0.0.1
 * @author Kevin Pirnie <me@kpirnie.com>
 * @package US Star Gazers Plugin
 * 
*/

// We don't want to allow direct access to this
defined( 'ABSPATH' ) || die( 'No direct script access allowed' );

// Make sure this class doesn't already exist
if( ! class_exists( 'SGU_Blocks' ) ) {

    /** 
     * Class SGU_Blocks
     * 
     * Registers and manages Gutenberg blocks for displaying astronomy data.
     * Each block wraps existing shortcode functionality to maintain consistency
     * between block-based and shortcode-based implementations.
     * 
     * Available blocks:
     * - sgup/latest-alerts: Display latest astronomy alerts with customizable title
     * - sgup/cme-alerts: Coronal Mass Ejection alerts with pagination
     * - sgup/flare-alerts: Solar flare alerts with pagination
     * - sgup/sw-alerts: Space weather alerts with pagination
     * - sgup/geomag-alerts: Geomagnetic storm alerts with pagination
     * - sgup/astro-menu: Navigation menu for astronomy sections
     * - sgup/neos: Near Earth Objects data with optional map display
     * - sgup/apod: Astronomy Picture of the Day
     * 
     * @since 0.0.1
     * @access public
     * @author Kevin Pirnie <me@kpirnie.com>
     * @package US Star Gazers Plugin
     * 
    */
    class SGU_Blocks {

        /** 
         * init
         * 
         * Initialize the blocks system by registering WordPress hooks.
         * This method sets up both the block registration and editor asset enqueuing.
         * Must be called early in the WordPress init sequence (priority < 10).
         * 
         * @since 0.0.1
         * @access public
         * @author Kevin Pirnie <me@kpirnie.com>
         * @package US Star Gazers Plugin
         * 
         * @return void This method does not return anything
         * 
        */
        public function init( ): void {

            // Register all blocks during WordPress initialization
            // This must happen before WordPress processes blocks on pages
            add_action( 'init', [ $this, 'register_blocks' ] );
            
            // Enqueue JavaScript for block editor previews and controls
            // Only loads in wp-admin block editor, not on front-end
            add_action( 'enqueue_block_editor_assets', [ $this, 'enqueue_editor_assets' ] );

            // Hook into the filter
            add_filter( 'block_categories_all', [ $this, 'register_block_categories' ], 5, 2 );

        }

        /** 
         * enqueue_editor_assets
         * 
         * Enqueue JavaScript and dependencies for the block editor.
         * Loads the compiled blocks.js file with all block registrations,
         * edit functions, and save functions for the Gutenberg editor.
         * 
         * The asset file (blocks.asset.php) is generated by webpack and contains
         * the correct dependencies and version hash for cache busting.
         * 
         * @since 0.0.1
         * @access public
         * @author Kevin Pirnie <me@kpirnie.com>
         * @package US Star Gazers Plugin
         * 
         * @return void This method does not return anything
         * 
        */
        public function enqueue_editor_assets( ): void {
    
            // Get the correct plugin directory URL
            $plugin_url = plugins_url( '/', SGUP_PATH . '/' . SGUP_FILENAME );
            
            // Build path to the webpack-generated asset file
            $asset_file = SGUP_PATH . '/build/blocks.asset.php';
            
            // Load asset file if it exists, otherwise use defaults
            $asset = file_exists( $asset_file ) ? require( $asset_file ) : [
                'dependencies' => ['wp-blocks', 'wp-element', 'wp-block-editor', 'wp-components', 'wp-i18n'],
                'version' => '1.0.0'
            ];

            // Enqueue the compiled blocks JavaScript for the editor
            wp_enqueue_script(
                'sgup-blocks-editor',
                $plugin_url . 'build/blocks.js',
                $asset['dependencies'],
                $asset['version'],
                true
            );
        }

        /** 
         * register_blocks
         * 
         * Register all Gutenberg blocks with WordPress.
         * Each block is registered with a render callback that delegates to existing
         * shortcode infrastructure, maintaining consistency between blocks and shortcodes.
         * 
         * Blocks are server-side rendered, meaning the render_callback generates
         * the HTML output on both front-end and in the editor preview.
         * 
         * @since 0.0.1
         * @access public
         * @author Kevin Pirnie <me@kpirnie.com>
         * @package US Star Gazers Plugin
         * 
         * @return void This method does not return anything
         * 
        */
        public function register_blocks( ): void {
            
            // Register Latest Alerts block
            // Displays the most recent astronomy alerts with a customizable title
            register_block_type( 'sgup/latest-alerts', [
                'api_version' => 2,
                'category' => 'sgup_space',
                'render_callback' => function( $attributes ) {

                    // Instantiate shortcode handler
                    $sc = new SGU_Alert_Shortcodes( );

                    // Delegate to existing shortcode render method
                    return $sc -> render_latest_alerts( [ 'title' => $attributes['title'] ?? 'Latest Astronomy Alerts', ], 
                        '', 'sgup_latest_alerts' );

                },
                'attributes' => [
                    'title' => ['type' => 'string', 'default' => 'Latest Astronomy Alerts']
                ]
            ] );

            // Register CME (Coronal Mass Ejection) Alerts block
            // Displays CME alerts with optional pagination controls
            register_block_type( 'sgup/cme-alerts', [
                'api_version' => 2,
                'category' => 'sgup_space',
                'render_callback' => function( $attributes ) {

                    // Instantiate shortcode handler
                    $sc = new SGU_Alert_Shortcodes();
                    
                    // Delegate to existing shortcode render method
                    // Converts block attributes to shortcode parameters
                    return $sc -> render_alert_shortcode( [
                        'show_paging' => $attributes['showPaging'] ?? false,
                        'paging_location' => $attributes['pagingLocation'] ?? 'bottom',
                        'per_page' => $attributes['perPage'] ?? 6
                    ], '', 'sgup_cme_alerts' );
                },
                'attributes' => [
                    'showPaging' => ['type' => 'boolean', 'default' => false],
                    'pagingLocation' => ['type' => 'string', 'default' => 'bottom', 'enum' => array( 'top', 'bottom', 'both' )],
                    'perPage' => ['type' => 'number', 'default' => 6]
                ]
            ] );

            // Register Solar Flare Alerts block
            // Displays solar flare event data with optional pagination
            register_block_type( 'sgup/flare-alerts', [
                'api_version' => 2,
                'category' => 'sgup_space',
                'render_callback' => function( $attributes ) {

                    // Instantiate shortcode handler
                    $sc = new SGU_Alert_Shortcodes();
                    
                    // Delegate to existing shortcode render method
                    return $sc -> render_alert_shortcode( [
                        'show_paging' => $attributes['showPaging'] ?? false,
                        'paging_location' => $attributes['pagingLocation'] ?? 'bottom',
                        'per_page' => $attributes['perPage'] ?? 6
                    ], '', 'sgup_flare_alerts' );
                },
                'attributes' => [
                    'showPaging' => ['type' => 'boolean', 'default' => false],
                    'pagingLocation' => ['type' => 'string', 'default' => 'bottom', 'enum' => array( 'top', 'bottom', 'both' )],
                    'perPage' => ['type' => 'number', 'default' => 6]
                ]
            ] );

            // Register Space Weather Alerts block
            // Displays general space weather notifications with pagination
            register_block_type( 'sgup/sw-alerts', [
                'api_version' => 2,
                'category' => 'sgup_space',
                'render_callback' => function( $attributes ) {

                    // Instantiate shortcode handler
                    $sc = new SGU_Alert_Shortcodes();
                    
                    // Delegate to existing shortcode render method
                    return $sc -> render_alert_shortcode( [
                        'show_paging' => $attributes['showPaging'] ?? false,
                        'paging_location' => $attributes['pagingLocation'] ?? 'bottom',
                        'per_page' => $attributes['perPage'] ?? 6
                    ], '', 'sgup_sw_alerts' );
                },
                'attributes' => [
                    'showPaging' => ['type' => 'boolean', 'default' => false],
                    'pagingLocation' => ['type' => 'string', 'default' => 'bottom', 'enum' => array( 'top', 'bottom', 'both' )],
                    'perPage' => ['type' => 'number', 'default' => 6]
                ]
            ] );

            // Register Geomagnetic Storm Alerts block
            // Displays geomagnetic activity alerts with pagination options
            register_block_type( 'sgup/geomag-alerts', [
                'api_version' => 2,
                'category' => 'sgup_space',
                'render_callback' => function( $attributes ) {

                    // Instantiate shortcode handler
                    $sc = new SGU_Alert_Shortcodes();
                    
                    // Delegate to existing shortcode render method
                    return $sc -> render_alert_shortcode( [
                        'show_paging' => $attributes['showPaging'] ?? false,
                        'paging_location' => $attributes['pagingLocation'] ?? 'bottom',
                        'per_page' => $attributes['perPage'] ?? 6
                    ], '', 'sgup_geomag_alerts' );
                },
                'attributes' => [
                    'showPaging' => ['type' => 'boolean', 'default' => false],
                    'pagingLocation' => ['type' => 'string', 'default' => 'bottom', 'enum' => array( 'top', 'bottom', 'both' )],
                    'perPage' => ['type' => 'number', 'default' => 6]
                ]
            ] );

            // Register Astronomy Menu block
            // Displays navigation menu for astronomy sections
            // 'which' attribute determines which menu variation to show
            register_block_type( 'sgup/astro-menu', [
                'api_version' => 2,
                'category' => 'sgup_space',
                'render_callback' => function( $attributes ) {

                    // Instantiate astronomy shortcode handler
                    $sc = new SGU_Astro_Shortcodes();
                    
                    // Delegate to menu generation method
                    return $sc -> add_astro_nav( [
                        'which' => $attributes['which'] ?? 'alert-menu', 
                        'is_inline' => $attributes['is_inline'] ?? false, 
                        'text_align' => $attributes['text_align'] ?? 'left'] );
                },
                'attributes' => [
                    'which' => ['type' => 'string', 'default' => 'alert-menu'],
                    'text_align' => ['type' => 'string', 'default' => 'left'],
                    'is_inline' => ['type' => 'boolean', 'default' => false],
                ]
            ] );

            // Register Near Earth Objects (NEO) block
            // Displays NEO tracking data with optional map visualization and pagination
            register_block_type( 'sgup/neos', [
                'api_version' => 2,
                'category' => 'sgup_space',
                'render_callback' => function( $attributes ) {

                    // Instantiate astronomy shortcode handler
                    $sc = new SGU_Astro_Shortcodes();
                    
                    // Delegate to NEO display method
                    // Includes map toggle for orbital visualization
                    return $sc -> add_neos( [
                        'show_paging' => $attributes['showPaging'] ?? false,
                        'show_map' => $attributes['showMap'] ?? false,
                        'paging_location' => $attributes['pagingLocation'] ?? 'bottom',
                        'per_page' => $attributes['perPage'] ?? 6
                    ] );
                },
                'attributes' => [
                    'showPaging' => ['type' => 'boolean', 'default' => false],
                    'showMap' => ['type' => 'boolean', 'default' => false],
                    'pagingLocation' => ['type' => 'string', 'default' => 'bottom', 'enum' => array( 'top', 'bottom', 'both' )],
                    'perPage' => ['type' => 'number', 'default' => 6]
                ]
            ] );

            // Register Astronomy Picture of the Day (APOD) block
            // Displays NASA's APOD with image and description
            register_block_type( 'sgup/apod', [
                'api_version' => 2,
                'category' => 'sgup_space',
                'render_callback' => function( $attributes ) {

                    // Instantiate astronomy shortcode handler
                    $sc = new SGU_Astro_Shortcodes();
                    
                    // Delegate to APOD display method with title
                    return $sc -> add_latest_apod( ['title' => $attributes['title'] ?? 'Astronomy Picture of the Day'] );
                },
                'attributes' => [
                    'title' => ['type' => 'string', 'default' => 'Astronomy Picture of the Day']
                ]
            ] );

        }

        /** 
         * register_block_categories
         * 
         * Register custom block categories
         * 
         * @since 0.0.1
         * @access public
         * @author Kevin Pirnie <me@kpirnie.com>
         * @package US Star Gazers Plugin
         * 
         * @param array $categories Existing block categories
         * 
         * @return array Modified block categories
         * 
        */
        public function register_block_categories( $categories, $post ) : array {

            // merge our new categories in with the existing ones
            $all_categories = array_merge(
                [
                    [
                        'slug'  => 'sgup_space',
                        'title' => __( 'Space', 'sgup' ),
                    ],
                    [
                        'slug'  => 'sgup_weather',
                        'title' => __( 'Weather', 'sgup' ),
                    ],
                ],
                $categories
            );

            // return them
            return $all_categories;
        }

    }
}